/* Generated by tools/build_assets.py. */
window.PORTFOLIO_PROJECTS = [
  {
    "id": "p-2026-01",
    "year": 2026,
    "name": "VNA",
    "cover": {
      "src": "assets/projects/p-2026-01/image-01-w1200.webp",
      "srcset": "assets/projects/p-2026-01/image-01-w640.webp 640w, assets/projects/p-2026-01/image-01-w1200.webp 715w, assets/projects/p-2026-01/image-01-w1600.webp 715w",
      "avifSrcset": "assets/projects/p-2026-01/image-01-w640.avif 640w, assets/projects/p-2026-01/image-01-w1200.avif 715w, assets/projects/p-2026-01/image-01-w1600.avif 715w",
      "width": 715,
      "height": 1350,
      "alt": "VNA 项目作品 1"
    },
    "images": [
      {
        "src": "assets/projects/p-2026-01/image-01-w1200.webp",
        "srcset": "assets/projects/p-2026-01/image-01-w640.webp 640w, assets/projects/p-2026-01/image-01-w1200.webp 715w, assets/projects/p-2026-01/image-01-w1600.webp 715w",
        "avifSrcset": "assets/projects/p-2026-01/image-01-w640.avif 640w, assets/projects/p-2026-01/image-01-w1200.avif 715w, assets/projects/p-2026-01/image-01-w1600.avif 715w",
        "width": 715,
        "height": 1350,
        "alt": "VNA 项目作品 1"
      }
    ]
  },
  {
    "id": "p-2026-02",
    "year": 2026,
    "name": "梵蒂斯",
    "cover": {
      "src": "assets/projects/p-2026-02/image-01-w1200.webp",
      "srcset": "assets/projects/p-2026-02/image-01-w640.webp 640w, assets/projects/p-2026-02/image-01-w1200.webp 1200w, assets/projects/p-2026-02/image-01-w1600.webp 1600w",
      "avifSrcset": "assets/projects/p-2026-02/image-01-w640.avif 640w, assets/projects/p-2026-02/image-01-w1200.avif 1200w, assets/projects/p-2026-02/image-01-w1600.avif 1600w",
      "width": 1822,
      "height": 1020,
      "alt": "梵蒂斯 项目作品 1"
    },
    "images": [
      {
        "src": "assets/projects/p-2026-02/image-01-w1200.webp",
        "srcset": "assets/projects/p-2026-02/image-01-w640.webp 640w, assets/projects/p-2026-02/image-01-w1200.webp 1200w, assets/projects/p-2026-02/image-01-w1600.webp 1600w",
        "avifSrcset": "assets/projects/p-2026-02/image-01-w640.avif 640w, assets/projects/p-2026-02/image-01-w1200.avif 1200w, assets/projects/p-2026-02/image-01-w1600.avif 1600w",
        "width": 1822,
        "height": 1020,
        "alt": "梵蒂斯 项目作品 1"
      },
      {
        "src": "assets/projects/p-2026-02/image-02-d2400.webp",
        "srcset": "assets/projects/p-2026-02/image-02-d1200.webp 1200w, assets/projects/p-2026-02/image-02-d2400.webp 2400w",
        "avifSrcset": "assets/projects/p-2026-02/image-02-d1200.avif 1200w, assets/projects/p-2026-02/image-02-d2400.avif 2400w",
        "width": 3387,
        "height": 1905,
        "alt": "梵蒂斯 项目作品 2"
      }
    ]
  },
  {
    "id": "p-2026-03",
    "year": 2026,
    "name": "英氏",
    "cover": {
      "src": "assets/projects/p-2026-03/image-01-w1200.webp",
      "srcset": "assets/projects/p-2026-03/image-01-w640.webp 640w, assets/projects/p-2026-03/image-01-w1200.webp 1200w, assets/projects/p-2026-03/image-01-w1600.webp 1600w",
      "avifSrcset": "assets/projects/p-2026-03/image-01-w640.avif 640w, assets/projects/p-2026-03/image-01-w1200.avif 1200w, assets/projects/p-2026-03/image-01-w1600.avif 1600w",
      "width": 1688,
      "height": 3000,
      "alt": "英氏 项目作品 1"
    },
    "images": [
      {
        "src": "assets/projects/p-2026-03/image-01-w1200.webp",
        "srcset": "assets/projects/p-2026-03/image-01-w640.webp 640w, assets/projects/p-2026-03/image-01-w1200.webp 1200w, assets/projects/p-2026-03/image-01-w1600.webp 1600w",
        "avifSrcset": "assets/projects/p-2026-03/image-01-w640.avif 640w, assets/projects/p-2026-03/image-01-w1200.avif 1200w, assets/projects/p-2026-03/image-01-w1600.avif 1600w",
        "width": 1688,
        "height": 3000,
        "alt": "英氏 项目作品 1"
      },
      {
        "src": "assets/projects/p-2026-03/image-02-d2400.webp",
        "srcset": "assets/projects/p-2026-03/image-02-d1200.webp 1200w, assets/projects/p-2026-03/image-02-d2400.webp 2000w",
        "avifSrcset": "assets/projects/p-2026-03/image-02-d1200.avif 1200w, assets/projects/p-2026-03/image-02-d2400.avif 2000w",
        "width": 2000,
        "height": 2000,
        "alt": "英氏 项目作品 2"
      }
    ]
  },
  {
    "id": "p-2025-01",
    "year": 2025,
    "name": "VNA",
    "cover": {
      "src": "assets/projects/p-2025-01/image-01-w1200.webp",
      "srcset": "assets/projects/p-2025-01/image-01-w640.webp 640w, assets/projects/p-2025-01/image-01-w1200.webp 1200w, assets/projects/p-2025-01/image-01-w1600.webp 1600w",
      "avifSrcset": "assets/projects/p-2025-01/image-01-w640.avif 640w, assets/projects/p-2025-01/image-01-w1200.avif 1200w, assets/projects/p-2025-01/image-01-w1600.avif 1600w",
      "width": 2456,
      "height": 4175,
      "alt": "VNA 项目作品 1"
    },
    "images": [
      {
        "src": "assets/projects/p-2025-01/image-01-w1200.webp",
        "srcset": "assets/projects/p-2025-01/image-01-w640.webp 640w, assets/projects/p-2025-01/image-01-w1200.webp 1200w, assets/projects/p-2025-01/image-01-w1600.webp 1600w",
        "avifSrcset": "assets/projects/p-2025-01/image-01-w640.avif 640w, assets/projects/p-2025-01/image-01-w1200.avif 1200w, assets/projects/p-2025-01/image-01-w1600.avif 1600w",
        "width": 2456,
        "height": 4175,
        "alt": "VNA 项目作品 1"
      },
      {
        "src": "assets/projects/p-2025-01/image-02-d2400.webp",
        "srcset": "assets/projects/p-2025-01/image-02-d1200.webp 639w, assets/projects/p-2025-01/image-02-d2400.webp 1278w",
        "avifSrcset": "assets/projects/p-2025-01/image-02-d1200.avif 639w, assets/projects/p-2025-01/image-02-d2400.avif 1278w",
        "width": 2459,
        "height": 4619,
        "alt": "VNA 项目作品 2"
      },
      {
        "src": "assets/projects/p-2025-01/image-03-d2400.webp",
        "srcset": "assets/projects/p-2025-01/image-03-d1200.webp 900w, assets/projects/p-2025-01/image-03-d2400.webp 1125w",
        "avifSrcset": "assets/projects/p-2025-01/image-03-d1200.avif 900w, assets/projects/p-2025-01/image-03-d2400.avif 1125w",
        "width": 1125,
        "height": 1500,
        "alt": "VNA 项目作品 3"
      },
      {
        "src": "assets/projects/p-2025-01/image-04-d2400.webp",
        "srcset": "assets/projects/p-2025-01/image-04-d1200.webp 553w, assets/projects/p-2025-01/image-04-d2400.webp 1105w",
        "avifSrcset": "assets/projects/p-2025-01/image-04-d1200.avif 553w, assets/projects/p-2025-01/image-04-d2400.avif 1105w",
        "width": 2462,
        "height": 5347,
        "alt": "VNA 项目作品 4"
      },
      {
        "src": "assets/projects/p-2025-01/image-05-d2400.webp",
        "srcset": "assets/projects/p-2025-01/image-05-d1200.webp 1124w, assets/projects/p-2025-01/image-05-d2400.webp 2249w",
        "avifSrcset": "assets/projects/p-2025-01/image-05-d1200.avif 1124w, assets/projects/p-2025-01/image-05-d2400.avif 2249w",
        "width": 2560,
        "height": 2732,
        "alt": "VNA 项目作品 5"
      }
    ]
  },
  {
    "id": "p-2025-02",
    "year": 2025,
    "name": "WHC",
    "cover": {
      "src": "assets/projects/p-2025-02/image-01-w1200.webp",
      "srcset": "assets/projects/p-2025-02/image-01-w640.webp 640w, assets/projects/p-2025-02/image-01-w1200.webp 790w, assets/projects/p-2025-02/image-01-w1600.webp 790w",
      "avifSrcset": "assets/projects/p-2025-02/image-01-w640.avif 640w, assets/projects/p-2025-02/image-01-w1200.avif 790w, assets/projects/p-2025-02/image-01-w1600.avif 790w",
      "width": 790,
      "height": 1388,
      "alt": "WHC 项目作品 1"
    },
    "images": [
      {
        "src": "assets/projects/p-2025-02/image-01-w1200.webp",
        "srcset": "assets/projects/p-2025-02/image-01-w640.webp 640w, assets/projects/p-2025-02/image-01-w1200.webp 790w, assets/projects/p-2025-02/image-01-w1600.webp 790w",
        "avifSrcset": "assets/projects/p-2025-02/image-01-w640.avif 640w, assets/projects/p-2025-02/image-01-w1200.avif 790w, assets/projects/p-2025-02/image-01-w1600.avif 790w",
        "width": 790,
        "height": 1388,
        "alt": "WHC 项目作品 1"
      },
      {
        "src": "assets/projects/p-2025-02/image-02-d2400.webp",
        "srcset": "assets/projects/p-2025-02/image-02-d1200.webp 743w, assets/projects/p-2025-02/image-02-d2400.webp 790w",
        "avifSrcset": "assets/projects/p-2025-02/image-02-d1200.avif 743w, assets/projects/p-2025-02/image-02-d2400.avif 790w",
        "width": 790,
        "height": 1276,
        "alt": "WHC 项目作品 2"
      },
      {
        "src": "assets/projects/p-2025-02/image-03-d2400.webp",
        "srcset": "assets/projects/p-2025-02/image-03-d1200.webp 689w, assets/projects/p-2025-02/image-03-d2400.webp 790w",
        "avifSrcset": "assets/projects/p-2025-02/image-03-d1200.avif 689w, assets/projects/p-2025-02/image-03-d2400.avif 790w",
        "width": 790,
        "height": 1375,
        "alt": "WHC 项目作品 3"
      }
    ]
  },
  {
    "id": "p-2025-03",
    "year": 2025,
    "name": "世喜",
    "cover": {
      "src": "assets/projects/p-2025-03/image-01-w1200.webp",
      "srcset": "assets/projects/p-2025-03/image-01-w640.webp 640w, assets/projects/p-2025-03/image-01-w1200.webp 1200w, assets/projects/p-2025-03/image-01-w1600.webp 1600w",
      "avifSrcset": "assets/projects/p-2025-03/image-01-w640.avif 640w, assets/projects/p-2025-03/image-01-w1200.avif 1200w, assets/projects/p-2025-03/image-01-w1600.avif 1600w",
      "width": 2800,
      "height": 4604,
      "alt": "世喜 项目作品 1"
    },
    "images": [
      {
        "src": "assets/projects/p-2025-03/image-01-w1200.webp",
        "srcset": "assets/projects/p-2025-03/image-01-w640.webp 640w, assets/projects/p-2025-03/image-01-w1200.webp 1200w, assets/projects/p-2025-03/image-01-w1600.webp 1600w",
        "avifSrcset": "assets/projects/p-2025-03/image-01-w640.avif 640w, assets/projects/p-2025-03/image-01-w1200.avif 1200w, assets/projects/p-2025-03/image-01-w1600.avif 1600w",
        "width": 2800,
        "height": 4604,
        "alt": "世喜 项目作品 1"
      },
      {
        "src": "assets/projects/p-2025-03/image-02-d2400.webp",
        "srcset": "assets/projects/p-2025-03/image-02-d1200.webp 800w, assets/projects/p-2025-03/image-02-d2400.webp 1600w",
        "avifSrcset": "assets/projects/p-2025-03/image-02-d1200.avif 800w, assets/projects/p-2025-03/image-02-d2400.avif 1600w",
        "width": 1845,
        "height": 2767,
        "alt": "世喜 项目作品 2"
      },
      {
        "src": "assets/projects/p-2025-03/image-03-d2400.webp",
        "srcset": "assets/projects/p-2025-03/image-03-d1200.webp 1200w, assets/projects/p-2025-03/image-03-d2400.webp 2400w",
        "avifSrcset": "assets/projects/p-2025-03/image-03-d1200.avif 1200w, assets/projects/p-2025-03/image-03-d2400.avif 2400w",
        "width": 2560,
        "height": 1385,
        "alt": "世喜 项目作品 3"
      }
    ]
  },
  {
    "id": "p-2025-04",
    "year": 2025,
    "name": "东鹏",
    "cover": {
      "src": "assets/projects/p-2025-04/image-01-w1200.webp",
      "srcset": "assets/projects/p-2025-04/image-01-w640.webp 640w, assets/projects/p-2025-04/image-01-w1200.webp 1200w, assets/projects/p-2025-04/image-01-w1600.webp 1600w",
      "avifSrcset": "assets/projects/p-2025-04/image-01-w640.avif 640w, assets/projects/p-2025-04/image-01-w1200.avif 1200w, assets/projects/p-2025-04/image-01-w1600.avif 1600w",
      "width": 1920,
      "height": 1080,
      "alt": "东鹏 项目作品 1"
    },
    "images": [
      {
        "src": "assets/projects/p-2025-04/image-01-w1200.webp",
        "srcset": "assets/projects/p-2025-04/image-01-w640.webp 640w, assets/projects/p-2025-04/image-01-w1200.webp 1200w, assets/projects/p-2025-04/image-01-w1600.webp 1600w",
        "avifSrcset": "assets/projects/p-2025-04/image-01-w640.avif 640w, assets/projects/p-2025-04/image-01-w1200.avif 1200w, assets/projects/p-2025-04/image-01-w1600.avif 1600w",
        "width": 1920,
        "height": 1080,
        "alt": "东鹏 项目作品 1"
      }
    ]
  },
  {
    "id": "p-2025-05",
    "year": 2025,
    "name": "五丰",
    "cover": {
      "src": "assets/projects/p-2025-05/image-01-w1200.webp",
      "srcset": "assets/projects/p-2025-05/image-01-w640.webp 640w, assets/projects/p-2025-05/image-01-w1200.webp 1200w, assets/projects/p-2025-05/image-01-w1600.webp 1600w",
      "avifSrcset": "assets/projects/p-2025-05/image-01-w640.avif 640w, assets/projects/p-2025-05/image-01-w1200.avif 1200w, assets/projects/p-2025-05/image-01-w1600.avif 1600w",
      "width": 3000,
      "height": 2244,
      "alt": "五丰 项目作品 1"
    },
    "images": [
      {
        "src": "assets/projects/p-2025-05/image-01-w1200.webp",
        "srcset": "assets/projects/p-2025-05/image-01-w640.webp 640w, assets/projects/p-2025-05/image-01-w1200.webp 1200w, assets/projects/p-2025-05/image-01-w1600.webp 1600w",
        "avifSrcset": "assets/projects/p-2025-05/image-01-w640.avif 640w, assets/projects/p-2025-05/image-01-w1200.avif 1200w, assets/projects/p-2025-05/image-01-w1600.avif 1600w",
        "width": 3000,
        "height": 2244,
        "alt": "五丰 项目作品 1"
      }
    ]
  },
  {
    "id": "p-2025-06",
    "year": 2025,
    "name": "傅家俊",
    "cover": {
      "src": "assets/projects/p-2025-06/image-01-w1200.webp",
      "srcset": "assets/projects/p-2025-06/image-01-w640.webp 640w, assets/projects/p-2025-06/image-01-w1200.webp 1200w, assets/projects/p-2025-06/image-01-w1600.webp 1600w",
      "avifSrcset": "assets/projects/p-2025-06/image-01-w640.avif 640w, assets/projects/p-2025-06/image-01-w1200.avif 1200w, assets/projects/p-2025-06/image-01-w1600.avif 1600w",
      "width": 2875,
      "height": 3125,
      "alt": "傅家俊 项目作品 1"
    },
    "images": [
      {
        "src": "assets/projects/p-2025-06/image-01-w1200.webp",
        "srcset": "assets/projects/p-2025-06/image-01-w640.webp 640w, assets/projects/p-2025-06/image-01-w1200.webp 1200w, assets/projects/p-2025-06/image-01-w1600.webp 1600w",
        "avifSrcset": "assets/projects/p-2025-06/image-01-w640.avif 640w, assets/projects/p-2025-06/image-01-w1200.avif 1200w, assets/projects/p-2025-06/image-01-w1600.avif 1600w",
        "width": 2875,
        "height": 3125,
        "alt": "傅家俊 项目作品 1"
      }
    ]
  },
  {
    "id": "p-2025-07",
    "year": 2025,
    "name": "哞星人",
    "cover": {
      "src": "assets/projects/p-2025-07/image-01-w1200.webp",
      "srcset": "assets/projects/p-2025-07/image-01-w640.webp 640w, assets/projects/p-2025-07/image-01-w1200.webp 1200w, assets/projects/p-2025-07/image-01-w1600.webp 1440w",
      "avifSrcset": "assets/projects/p-2025-07/image-01-w640.avif 640w, assets/projects/p-2025-07/image-01-w1200.avif 1200w, assets/projects/p-2025-07/image-01-w1600.avif 1440w",
      "width": 1440,
      "height": 2560,
      "alt": "哞星人 项目作品 1"
    },
    "images": [
      {
        "src": "assets/projects/p-2025-07/image-01-w1200.webp",
        "srcset": "assets/projects/p-2025-07/image-01-w640.webp 640w, assets/projects/p-2025-07/image-01-w1200.webp 1200w, assets/projects/p-2025-07/image-01-w1600.webp 1440w",
        "avifSrcset": "assets/projects/p-2025-07/image-01-w640.avif 640w, assets/projects/p-2025-07/image-01-w1200.avif 1200w, assets/projects/p-2025-07/image-01-w1600.avif 1440w",
        "width": 1440,
        "height": 2560,
        "alt": "哞星人 项目作品 1"
      }
    ]
  },
  {
    "id": "p-2025-08",
    "year": 2025,
    "name": "最护",
    "cover": {
      "src": "assets/projects/p-2025-08/image-01-w1200.webp",
      "srcset": "assets/projects/p-2025-08/image-01-w640.webp 640w, assets/projects/p-2025-08/image-01-w1200.webp 1200w, assets/projects/p-2025-08/image-01-w1600.webp 1440w",
      "avifSrcset": "assets/projects/p-2025-08/image-01-w640.avif 640w, assets/projects/p-2025-08/image-01-w1200.avif 1200w, assets/projects/p-2025-08/image-01-w1600.avif 1440w",
      "width": 1440,
      "height": 2560,
      "alt": "最护 项目作品 1"
    },
    "images": [
      {
        "src": "assets/projects/p-2025-08/image-01-w1200.webp",
        "srcset": "assets/projects/p-2025-08/image-01-w640.webp 640w, assets/projects/p-2025-08/image-01-w1200.webp 1200w, assets/projects/p-2025-08/image-01-w1600.webp 1440w",
        "avifSrcset": "assets/projects/p-2025-08/image-01-w640.avif 640w, assets/projects/p-2025-08/image-01-w1200.avif 1200w, assets/projects/p-2025-08/image-01-w1600.avif 1440w",
        "width": 1440,
        "height": 2560,
        "alt": "最护 项目作品 1"
      },
      {
        "src": "assets/projects/p-2025-08/image-02-d2400.webp",
        "srcset": "assets/projects/p-2025-08/image-02-d1200.webp 675w, assets/projects/p-2025-08/image-02-d2400.webp 1070w",
        "avifSrcset": "assets/projects/p-2025-08/image-02-d1200.avif 675w, assets/projects/p-2025-08/image-02-d2400.avif 1070w",
        "width": 1070,
        "height": 1903,
        "alt": "最护 项目作品 2"
      }
    ]
  },
  {
    "id": "p-2025-09",
    "year": 2025,
    "name": "植沁",
    "cover": {
      "src": "assets/projects/p-2025-09/image-01-w1200.webp",
      "srcset": "assets/projects/p-2025-09/image-01-w640.webp 640w, assets/projects/p-2025-09/image-01-w1200.webp 1200w, assets/projects/p-2025-09/image-01-w1600.webp 1600w",
      "avifSrcset": "assets/projects/p-2025-09/image-01-w640.avif 640w, assets/projects/p-2025-09/image-01-w1200.avif 1200w, assets/projects/p-2025-09/image-01-w1600.avif 1600w",
      "width": 1920,
      "height": 1080,
      "alt": "植沁 项目作品 1"
    },
    "images": [
      {
        "src": "assets/projects/p-2025-09/image-01-w1200.webp",
        "srcset": "assets/projects/p-2025-09/image-01-w640.webp 640w, assets/projects/p-2025-09/image-01-w1200.webp 1200w, assets/projects/p-2025-09/image-01-w1600.webp 1600w",
        "avifSrcset": "assets/projects/p-2025-09/image-01-w640.avif 640w, assets/projects/p-2025-09/image-01-w1200.avif 1200w, assets/projects/p-2025-09/image-01-w1600.avif 1600w",
        "width": 1920,
        "height": 1080,
        "alt": "植沁 项目作品 1"
      }
    ]
  },
  {
    "id": "p-2025-10",
    "year": 2025,
    "name": "植物妈妈",
    "cover": {
      "src": "assets/projects/p-2025-10/image-01-w1200.webp",
      "srcset": "assets/projects/p-2025-10/image-01-w640.webp 640w, assets/projects/p-2025-10/image-01-w1200.webp 1200w, assets/projects/p-2025-10/image-01-w1600.webp 1600w",
      "avifSrcset": "assets/projects/p-2025-10/image-01-w640.avif 640w, assets/projects/p-2025-10/image-01-w1200.avif 1200w, assets/projects/p-2025-10/image-01-w1600.avif 1600w",
      "width": 1875,
      "height": 2500,
      "alt": "植物妈妈 项目作品 1"
    },
    "images": [
      {
        "src": "assets/projects/p-2025-10/image-01-w1200.webp",
        "srcset": "assets/projects/p-2025-10/image-01-w640.webp 640w, assets/projects/p-2025-10/image-01-w1200.webp 1200w, assets/projects/p-2025-10/image-01-w1600.webp 1600w",
        "avifSrcset": "assets/projects/p-2025-10/image-01-w640.avif 640w, assets/projects/p-2025-10/image-01-w1200.avif 1200w, assets/projects/p-2025-10/image-01-w1600.avif 1600w",
        "width": 1875,
        "height": 2500,
        "alt": "植物妈妈 项目作品 1"
      }
    ]
  },
  {
    "id": "p-2025-11",
    "year": 2025,
    "name": "百岁密码",
    "cover": {
      "src": "assets/projects/p-2025-11/image-01-w1200.webp",
      "srcset": "assets/projects/p-2025-11/image-01-w640.webp 640w, assets/projects/p-2025-11/image-01-w1200.webp 1200w, assets/projects/p-2025-11/image-01-w1600.webp 1600w",
      "avifSrcset": "assets/projects/p-2025-11/image-01-w640.avif 640w, assets/projects/p-2025-11/image-01-w1200.avif 1200w, assets/projects/p-2025-11/image-01-w1600.avif 1600w",
      "width": 3387,
      "height": 1905,
      "alt": "百岁密码 项目作品 1"
    },
    "images": [
      {
        "src": "assets/projects/p-2025-11/image-01-w1200.webp",
        "srcset": "assets/projects/p-2025-11/image-01-w640.webp 640w, assets/projects/p-2025-11/image-01-w1200.webp 1200w, assets/projects/p-2025-11/image-01-w1600.webp 1600w",
        "avifSrcset": "assets/projects/p-2025-11/image-01-w640.avif 640w, assets/projects/p-2025-11/image-01-w1200.avif 1200w, assets/projects/p-2025-11/image-01-w1600.avif 1600w",
        "width": 3387,
        "height": 1905,
        "alt": "百岁密码 项目作品 1"
      }
    ]
  },
  {
    "id": "p-2025-12",
    "year": 2025,
    "name": "纳屿",
    "cover": {
      "src": "assets/projects/p-2025-12/image-01-w1200.webp",
      "srcset": "assets/projects/p-2025-12/image-01-w640.webp 640w, assets/projects/p-2025-12/image-01-w1200.webp 1200w, assets/projects/p-2025-12/image-01-w1600.webp 1600w",
      "avifSrcset": "assets/projects/p-2025-12/image-01-w640.avif 640w, assets/projects/p-2025-12/image-01-w1200.avif 1200w, assets/projects/p-2025-12/image-01-w1600.avif 1600w",
      "width": 3840,
      "height": 2160,
      "alt": "纳屿 项目作品 1"
    },
    "images": [
      {
        "src": "assets/projects/p-2025-12/image-01-w1200.webp",
        "srcset": "assets/projects/p-2025-12/image-01-w640.webp 640w, assets/projects/p-2025-12/image-01-w1200.webp 1200w, assets/projects/p-2025-12/image-01-w1600.webp 1600w",
        "avifSrcset": "assets/projects/p-2025-12/image-01-w640.avif 640w, assets/projects/p-2025-12/image-01-w1200.avif 1200w, assets/projects/p-2025-12/image-01-w1600.avif 1600w",
        "width": 3840,
        "height": 2160,
        "alt": "纳屿 项目作品 1"
      }
    ]
  },
  {
    "id": "p-2025-13",
    "year": 2025,
    "name": "轩妈",
    "cover": {
      "src": "assets/projects/p-2025-13/image-01-w1200.webp",
      "srcset": "assets/projects/p-2025-13/image-01-w640.webp 640w, assets/projects/p-2025-13/image-01-w1200.webp 1200w, assets/projects/p-2025-13/image-01-w1600.webp 1600w",
      "avifSrcset": "assets/projects/p-2025-13/image-01-w640.avif 640w, assets/projects/p-2025-13/image-01-w1200.avif 1200w, assets/projects/p-2025-13/image-01-w1600.avif 1600w",
      "width": 2560,
      "height": 1440,
      "alt": "轩妈 项目作品 1"
    },
    "images": [
      {
        "src": "assets/projects/p-2025-13/image-01-w1200.webp",
        "srcset": "assets/projects/p-2025-13/image-01-w640.webp 640w, assets/projects/p-2025-13/image-01-w1200.webp 1200w, assets/projects/p-2025-13/image-01-w1600.webp 1600w",
        "avifSrcset": "assets/projects/p-2025-13/image-01-w640.avif 640w, assets/projects/p-2025-13/image-01-w1200.avif 1200w, assets/projects/p-2025-13/image-01-w1600.avif 1600w",
        "width": 2560,
        "height": 1440,
        "alt": "轩妈 项目作品 1"
      }
    ]
  },
  {
    "id": "p-2025-14",
    "year": 2025,
    "name": "锦囊",
    "cover": {
      "src": "assets/projects/p-2025-14/image-01-w1200.webp",
      "srcset": "assets/projects/p-2025-14/image-01-w640.webp 640w, assets/projects/p-2025-14/image-01-w1200.webp 1200w, assets/projects/p-2025-14/image-01-w1600.webp 1214w",
      "avifSrcset": "assets/projects/p-2025-14/image-01-w640.avif 640w, assets/projects/p-2025-14/image-01-w1200.avif 1200w, assets/projects/p-2025-14/image-01-w1600.avif 1214w",
      "width": 1214,
      "height": 1905,
      "alt": "锦囊 项目作品 1"
    },
    "images": [
      {
        "src": "assets/projects/p-2025-14/image-01-w1200.webp",
        "srcset": "assets/projects/p-2025-14/image-01-w640.webp 640w, assets/projects/p-2025-14/image-01-w1200.webp 1200w, assets/projects/p-2025-14/image-01-w1600.webp 1214w",
        "avifSrcset": "assets/projects/p-2025-14/image-01-w640.avif 640w, assets/projects/p-2025-14/image-01-w1200.avif 1200w, assets/projects/p-2025-14/image-01-w1600.avif 1214w",
        "width": 1214,
        "height": 1905,
        "alt": "锦囊 项目作品 1"
      }
    ]
  },
  {
    "id": "p-2025-15",
    "year": 2025,
    "name": "雪湃",
    "cover": {
      "src": "assets/projects/p-2025-15/image-01-w1200.webp",
      "srcset": "assets/projects/p-2025-15/image-01-w640.webp 640w, assets/projects/p-2025-15/image-01-w1200.webp 1200w, assets/projects/p-2025-15/image-01-w1600.webp 1600w",
      "avifSrcset": "assets/projects/p-2025-15/image-01-w640.avif 640w, assets/projects/p-2025-15/image-01-w1200.avif 1200w, assets/projects/p-2025-15/image-01-w1600.avif 1600w",
      "width": 2560,
      "height": 1770,
      "alt": "雪湃 项目作品 1"
    },
    "images": [
      {
        "src": "assets/projects/p-2025-15/image-01-w1200.webp",
        "srcset": "assets/projects/p-2025-15/image-01-w640.webp 640w, assets/projects/p-2025-15/image-01-w1200.webp 1200w, assets/projects/p-2025-15/image-01-w1600.webp 1600w",
        "avifSrcset": "assets/projects/p-2025-15/image-01-w640.avif 640w, assets/projects/p-2025-15/image-01-w1200.avif 1200w, assets/projects/p-2025-15/image-01-w1600.avif 1600w",
        "width": 2560,
        "height": 1770,
        "alt": "雪湃 项目作品 1"
      },
      {
        "src": "assets/projects/p-2025-15/image-02-d2400.webp",
        "srcset": "assets/projects/p-2025-15/image-02-d1200.webp 1200w, assets/projects/p-2025-15/image-02-d2400.webp 2400w",
        "avifSrcset": "assets/projects/p-2025-15/image-02-d1200.avif 1200w, assets/projects/p-2025-15/image-02-d2400.avif 2400w",
        "width": 2560,
        "height": 1770,
        "alt": "雪湃 项目作品 2"
      }
    ]
  },
  {
    "id": "p-2024-01",
    "year": 2024,
    "name": "3i",
    "cover": {
      "src": "assets/projects/p-2024-01/image-01-w1200.webp",
      "srcset": "assets/projects/p-2024-01/image-01-w640.webp 640w, assets/projects/p-2024-01/image-01-w1200.webp 1200w, assets/projects/p-2024-01/image-01-w1600.webp 1548w",
      "avifSrcset": "assets/projects/p-2024-01/image-01-w640.avif 640w, assets/projects/p-2024-01/image-01-w1200.avif 1200w, assets/projects/p-2024-01/image-01-w1600.avif 1548w",
      "width": 1548,
      "height": 3200,
      "alt": "3i 项目作品 1"
    },
    "images": [
      {
        "src": "assets/projects/p-2024-01/image-01-w1200.webp",
        "srcset": "assets/projects/p-2024-01/image-01-w640.webp 640w, assets/projects/p-2024-01/image-01-w1200.webp 1200w, assets/projects/p-2024-01/image-01-w1600.webp 1548w",
        "avifSrcset": "assets/projects/p-2024-01/image-01-w640.avif 640w, assets/projects/p-2024-01/image-01-w1200.avif 1200w, assets/projects/p-2024-01/image-01-w1600.avif 1548w",
        "width": 1548,
        "height": 3200,
        "alt": "3i 项目作品 1"
      },
      {
        "src": "assets/projects/p-2024-01/image-02-d2400.webp",
        "srcset": "assets/projects/p-2024-01/image-02-d1200.webp 675w, assets/projects/p-2024-01/image-02-d2400.webp 1080w",
        "avifSrcset": "assets/projects/p-2024-01/image-02-d1200.avif 675w, assets/projects/p-2024-01/image-02-d2400.avif 1080w",
        "width": 1080,
        "height": 1920,
        "alt": "3i 项目作品 2"
      },
      {
        "src": "assets/projects/p-2024-01/image-03-d2400.webp",
        "srcset": "assets/projects/p-2024-01/image-03-d1200.webp 730w, assets/projects/p-2024-01/image-03-d2400.webp 1400w",
        "avifSrcset": "assets/projects/p-2024-01/image-03-d1200.avif 730w, assets/projects/p-2024-01/image-03-d2400.avif 1400w",
        "width": 1400,
        "height": 2300,
        "alt": "3i 项目作品 3"
      }
    ]
  },
  {
    "id": "p-2024-02",
    "year": 2024,
    "name": "Downplus",
    "cover": {
      "src": "assets/projects/p-2024-02/image-01-w1200.webp",
      "srcset": "assets/projects/p-2024-02/image-01-w640.webp 640w, assets/projects/p-2024-02/image-01-w1200.webp 1200w, assets/projects/p-2024-02/image-01-w1600.webp 1600w",
      "avifSrcset": "assets/projects/p-2024-02/image-01-w640.avif 640w, assets/projects/p-2024-02/image-01-w1200.avif 1200w, assets/projects/p-2024-02/image-01-w1600.avif 1600w",
      "width": 3387,
      "height": 1905,
      "alt": "Downplus 项目作品 1"
    },
    "images": [
      {
        "src": "assets/projects/p-2024-02/image-01-w1200.webp",
        "srcset": "assets/projects/p-2024-02/image-01-w640.webp 640w, assets/projects/p-2024-02/image-01-w1200.webp 1200w, assets/projects/p-2024-02/image-01-w1600.webp 1600w",
        "avifSrcset": "assets/projects/p-2024-02/image-01-w640.avif 640w, assets/projects/p-2024-02/image-01-w1200.avif 1200w, assets/projects/p-2024-02/image-01-w1600.avif 1600w",
        "width": 3387,
        "height": 1905,
        "alt": "Downplus 项目作品 1"
      }
    ]
  },
  {
    "id": "p-2024-03",
    "year": 2024,
    "name": "五丰",
    "cover": {
      "src": "assets/projects/p-2024-03/image-01-w1200.webp",
      "srcset": "assets/projects/p-2024-03/image-01-w640.webp 640w, assets/projects/p-2024-03/image-01-w1200.webp 1000w, assets/projects/p-2024-03/image-01-w1600.webp 1000w",
      "avifSrcset": "assets/projects/p-2024-03/image-01-w640.avif 640w, assets/projects/p-2024-03/image-01-w1200.avif 1000w, assets/projects/p-2024-03/image-01-w1600.avif 1000w",
      "width": 1000,
      "height": 1360,
      "alt": "五丰 项目作品 1"
    },
    "images": [
      {
        "src": "assets/projects/p-2024-03/image-01-w1200.webp",
        "srcset": "assets/projects/p-2024-03/image-01-w640.webp 640w, assets/projects/p-2024-03/image-01-w1200.webp 1000w, assets/projects/p-2024-03/image-01-w1600.webp 1000w",
        "avifSrcset": "assets/projects/p-2024-03/image-01-w640.avif 640w, assets/projects/p-2024-03/image-01-w1200.avif 1000w, assets/projects/p-2024-03/image-01-w1600.avif 1000w",
        "width": 1000,
        "height": 1360,
        "alt": "五丰 项目作品 1"
      }
    ]
  },
  {
    "id": "p-2024-04",
    "year": 2024,
    "name": "凸凸棉",
    "cover": {
      "src": "assets/projects/p-2024-04/image-01-w1200.webp",
      "srcset": "assets/projects/p-2024-04/image-01-w640.webp 640w, assets/projects/p-2024-04/image-01-w1200.webp 1200w, assets/projects/p-2024-04/image-01-w1600.webp 1600w",
      "avifSrcset": "assets/projects/p-2024-04/image-01-w640.avif 640w, assets/projects/p-2024-04/image-01-w1200.avif 1200w, assets/projects/p-2024-04/image-01-w1600.avif 1600w",
      "width": 3840,
      "height": 2160,
      "alt": "凸凸棉 项目作品 1"
    },
    "images": [
      {
        "src": "assets/projects/p-2024-04/image-01-w1200.webp",
        "srcset": "assets/projects/p-2024-04/image-01-w640.webp 640w, assets/projects/p-2024-04/image-01-w1200.webp 1200w, assets/projects/p-2024-04/image-01-w1600.webp 1600w",
        "avifSrcset": "assets/projects/p-2024-04/image-01-w640.avif 640w, assets/projects/p-2024-04/image-01-w1200.avif 1200w, assets/projects/p-2024-04/image-01-w1600.avif 1600w",
        "width": 3840,
        "height": 2160,
        "alt": "凸凸棉 项目作品 1"
      },
      {
        "src": "assets/projects/p-2024-04/image-02-d2400.webp",
        "srcset": "assets/projects/p-2024-04/image-02-d1200.webp 1200w, assets/projects/p-2024-04/image-02-d2400.webp 2400w",
        "avifSrcset": "assets/projects/p-2024-04/image-02-d1200.avif 1200w, assets/projects/p-2024-04/image-02-d2400.avif 2400w",
        "width": 2560,
        "height": 1612,
        "alt": "凸凸棉 项目作品 2"
      }
    ]
  },
  {
    "id": "p-2024-05",
    "year": 2024,
    "name": "尼多熊",
    "cover": {
      "src": "assets/projects/p-2024-05/image-01-w1200.webp",
      "srcset": "assets/projects/p-2024-05/image-01-w640.webp 640w, assets/projects/p-2024-05/image-01-w1200.webp 1200w, assets/projects/p-2024-05/image-01-w1600.webp 1600w",
      "avifSrcset": "assets/projects/p-2024-05/image-01-w640.avif 640w, assets/projects/p-2024-05/image-01-w1200.avif 1200w, assets/projects/p-2024-05/image-01-w1600.avif 1600w",
      "width": 2560,
      "height": 1440,
      "alt": "尼多熊 项目作品 1"
    },
    "images": [
      {
        "src": "assets/projects/p-2024-05/image-01-w1200.webp",
        "srcset": "assets/projects/p-2024-05/image-01-w640.webp 640w, assets/projects/p-2024-05/image-01-w1200.webp 1200w, assets/projects/p-2024-05/image-01-w1600.webp 1600w",
        "avifSrcset": "assets/projects/p-2024-05/image-01-w640.avif 640w, assets/projects/p-2024-05/image-01-w1200.avif 1200w, assets/projects/p-2024-05/image-01-w1600.avif 1600w",
        "width": 2560,
        "height": 1440,
        "alt": "尼多熊 项目作品 1"
      }
    ]
  },
  {
    "id": "p-2024-06",
    "year": 2024,
    "name": "张雪",
    "cover": {
      "src": "assets/projects/p-2024-06/image-01-w1200.webp",
      "srcset": "assets/projects/p-2024-06/image-01-w640.webp 640w, assets/projects/p-2024-06/image-01-w1200.webp 1200w, assets/projects/p-2024-06/image-01-w1600.webp 1600w",
      "avifSrcset": "assets/projects/p-2024-06/image-01-w640.avif 640w, assets/projects/p-2024-06/image-01-w1200.avif 1200w, assets/projects/p-2024-06/image-01-w1600.avif 1600w",
      "width": 2339,
      "height": 1905,
      "alt": "张雪 项目作品 1"
    },
    "images": [
      {
        "src": "assets/projects/p-2024-06/image-01-w1200.webp",
        "srcset": "assets/projects/p-2024-06/image-01-w640.webp 640w, assets/projects/p-2024-06/image-01-w1200.webp 1200w, assets/projects/p-2024-06/image-01-w1600.webp 1600w",
        "avifSrcset": "assets/projects/p-2024-06/image-01-w640.avif 640w, assets/projects/p-2024-06/image-01-w1200.avif 1200w, assets/projects/p-2024-06/image-01-w1600.avif 1600w",
        "width": 2339,
        "height": 1905,
        "alt": "张雪 项目作品 1"
      }
    ]
  },
  {
    "id": "p-2024-07",
    "year": 2024,
    "name": "汪保来",
    "cover": {
      "src": "assets/projects/p-2024-07/image-01-w1200.webp",
      "srcset": "assets/projects/p-2024-07/image-01-w640.webp 640w, assets/projects/p-2024-07/image-01-w1200.webp 1200w, assets/projects/p-2024-07/image-01-w1600.webp 1600w",
      "avifSrcset": "assets/projects/p-2024-07/image-01-w640.avif 640w, assets/projects/p-2024-07/image-01-w1200.avif 1200w, assets/projects/p-2024-07/image-01-w1600.avif 1600w",
      "width": 2560,
      "height": 1440,
      "alt": "汪保来 项目作品 1"
    },
    "images": [
      {
        "src": "assets/projects/p-2024-07/image-01-w1200.webp",
        "srcset": "assets/projects/p-2024-07/image-01-w640.webp 640w, assets/projects/p-2024-07/image-01-w1200.webp 1200w, assets/projects/p-2024-07/image-01-w1600.webp 1600w",
        "avifSrcset": "assets/projects/p-2024-07/image-01-w640.avif 640w, assets/projects/p-2024-07/image-01-w1200.avif 1200w, assets/projects/p-2024-07/image-01-w1600.avif 1600w",
        "width": 2560,
        "height": 1440,
        "alt": "汪保来 项目作品 1"
      }
    ]
  },
  {
    "id": "p-2024-08",
    "year": 2024,
    "name": "燃籽",
    "cover": {
      "src": "assets/projects/p-2024-08/image-01-w1200.webp",
      "srcset": "assets/projects/p-2024-08/image-01-w640.webp 640w, assets/projects/p-2024-08/image-01-w1200.webp 1200w, assets/projects/p-2024-08/image-01-w1600.webp 1600w",
      "avifSrcset": "assets/projects/p-2024-08/image-01-w640.avif 640w, assets/projects/p-2024-08/image-01-w1200.avif 1200w, assets/projects/p-2024-08/image-01-w1600.avif 1600w",
      "width": 2419,
      "height": 1846,
      "alt": "燃籽 项目作品 1"
    },
    "images": [
      {
        "src": "assets/projects/p-2024-08/image-01-w1200.webp",
        "srcset": "assets/projects/p-2024-08/image-01-w640.webp 640w, assets/projects/p-2024-08/image-01-w1200.webp 1200w, assets/projects/p-2024-08/image-01-w1600.webp 1600w",
        "avifSrcset": "assets/projects/p-2024-08/image-01-w640.avif 640w, assets/projects/p-2024-08/image-01-w1200.avif 1200w, assets/projects/p-2024-08/image-01-w1600.avif 1600w",
        "width": 2419,
        "height": 1846,
        "alt": "燃籽 项目作品 1"
      }
    ]
  },
  {
    "id": "p-2024-09",
    "year": 2024,
    "name": "罗宾汉",
    "cover": {
      "src": "assets/projects/p-2024-09/image-01-w1200.webp",
      "srcset": "assets/projects/p-2024-09/image-01-w640.webp 640w, assets/projects/p-2024-09/image-01-w1200.webp 1200w, assets/projects/p-2024-09/image-01-w1600.webp 1600w",
      "avifSrcset": "assets/projects/p-2024-09/image-01-w640.avif 640w, assets/projects/p-2024-09/image-01-w1200.avif 1200w, assets/projects/p-2024-09/image-01-w1600.avif 1600w",
      "width": 2560,
      "height": 1508,
      "alt": "罗宾汉 项目作品 1"
    },
    "images": [
      {
        "src": "assets/projects/p-2024-09/image-01-w1200.webp",
        "srcset": "assets/projects/p-2024-09/image-01-w640.webp 640w, assets/projects/p-2024-09/image-01-w1200.webp 1200w, assets/projects/p-2024-09/image-01-w1600.webp 1600w",
        "avifSrcset": "assets/projects/p-2024-09/image-01-w640.avif 640w, assets/projects/p-2024-09/image-01-w1200.avif 1200w, assets/projects/p-2024-09/image-01-w1600.avif 1600w",
        "width": 2560,
        "height": 1508,
        "alt": "罗宾汉 项目作品 1"
      },
      {
        "src": "assets/projects/p-2024-09/image-02-d2400.webp",
        "srcset": "assets/projects/p-2024-09/image-02-d1200.webp 1200w, assets/projects/p-2024-09/image-02-d2400.webp 2400w",
        "avifSrcset": "assets/projects/p-2024-09/image-02-d1200.avif 1200w, assets/projects/p-2024-09/image-02-d2400.avif 2400w",
        "width": 5760,
        "height": 3205,
        "alt": "罗宾汉 项目作品 2"
      }
    ]
  },
  {
    "id": "p-2024-10",
    "year": 2024,
    "name": "金大福",
    "cover": {
      "src": "assets/projects/p-2024-10/image-01-w1200.webp",
      "srcset": "assets/projects/p-2024-10/image-01-w640.webp 640w, assets/projects/p-2024-10/image-01-w1200.webp 1200w, assets/projects/p-2024-10/image-01-w1600.webp 1600w",
      "avifSrcset": "assets/projects/p-2024-10/image-01-w640.avif 640w, assets/projects/p-2024-10/image-01-w1200.avif 1200w, assets/projects/p-2024-10/image-01-w1600.avif 1600w",
      "width": 3840,
      "height": 2160,
      "alt": "金大福 项目作品 1"
    },
    "images": [
      {
        "src": "assets/projects/p-2024-10/image-01-w1200.webp",
        "srcset": "assets/projects/p-2024-10/image-01-w640.webp 640w, assets/projects/p-2024-10/image-01-w1200.webp 1200w, assets/projects/p-2024-10/image-01-w1600.webp 1600w",
        "avifSrcset": "assets/projects/p-2024-10/image-01-w640.avif 640w, assets/projects/p-2024-10/image-01-w1200.avif 1200w, assets/projects/p-2024-10/image-01-w1600.avif 1600w",
        "width": 3840,
        "height": 2160,
        "alt": "金大福 项目作品 1"
      }
    ]
  },
  {
    "id": "p-2024-11",
    "year": 2024,
    "name": "鲸才",
    "cover": {
      "src": "assets/projects/p-2024-11/image-01-w1200.webp",
      "srcset": "assets/projects/p-2024-11/image-01-w640.webp 640w, assets/projects/p-2024-11/image-01-w1200.webp 1200w, assets/projects/p-2024-11/image-01-w1600.webp 1600w",
      "avifSrcset": "assets/projects/p-2024-11/image-01-w640.avif 640w, assets/projects/p-2024-11/image-01-w1200.avif 1200w, assets/projects/p-2024-11/image-01-w1600.avif 1600w",
      "width": 3387,
      "height": 1905,
      "alt": "鲸才 项目作品 1"
    },
    "images": [
      {
        "src": "assets/projects/p-2024-11/image-01-w1200.webp",
        "srcset": "assets/projects/p-2024-11/image-01-w640.webp 640w, assets/projects/p-2024-11/image-01-w1200.webp 1200w, assets/projects/p-2024-11/image-01-w1600.webp 1600w",
        "avifSrcset": "assets/projects/p-2024-11/image-01-w640.avif 640w, assets/projects/p-2024-11/image-01-w1200.avif 1200w, assets/projects/p-2024-11/image-01-w1600.avif 1600w",
        "width": 3387,
        "height": 1905,
        "alt": "鲸才 项目作品 1"
      }
    ]
  },
  {
    "id": "p-2023-01",
    "year": 2023,
    "name": "COCO",
    "cover": {
      "src": "assets/projects/p-2023-01/image-01-w1200.webp",
      "srcset": "assets/projects/p-2023-01/image-01-w640.webp 640w, assets/projects/p-2023-01/image-01-w1200.webp 1200w, assets/projects/p-2023-01/image-01-w1600.webp 1600w",
      "avifSrcset": "assets/projects/p-2023-01/image-01-w640.avif 640w, assets/projects/p-2023-01/image-01-w1200.avif 1200w, assets/projects/p-2023-01/image-01-w1600.avif 1600w",
      "width": 3387,
      "height": 1905,
      "alt": "COCO 项目作品 1"
    },
    "images": [
      {
        "src": "assets/projects/p-2023-01/image-01-w1200.webp",
        "srcset": "assets/projects/p-2023-01/image-01-w640.webp 640w, assets/projects/p-2023-01/image-01-w1200.webp 1200w, assets/projects/p-2023-01/image-01-w1600.webp 1600w",
        "avifSrcset": "assets/projects/p-2023-01/image-01-w640.avif 640w, assets/projects/p-2023-01/image-01-w1200.avif 1200w, assets/projects/p-2023-01/image-01-w1600.avif 1600w",
        "width": 3387,
        "height": 1905,
        "alt": "COCO 项目作品 1"
      },
      {
        "src": "assets/projects/p-2023-01/image-02-d2400.webp",
        "srcset": "assets/projects/p-2023-01/image-02-d1200.webp 1200w, assets/projects/p-2023-01/image-02-d2400.webp 2400w",
        "avifSrcset": "assets/projects/p-2023-01/image-02-d1200.avif 1200w, assets/projects/p-2023-01/image-02-d2400.avif 2400w",
        "width": 3387,
        "height": 1905,
        "alt": "COCO 项目作品 2"
      },
      {
        "src": "assets/projects/p-2023-01/image-03-d2400.webp",
        "srcset": "assets/projects/p-2023-01/image-03-d1200.webp 1200w, assets/projects/p-2023-01/image-03-d2400.webp 2400w",
        "avifSrcset": "assets/projects/p-2023-01/image-03-d1200.avif 1200w, assets/projects/p-2023-01/image-03-d2400.avif 2400w",
        "width": 3387,
        "height": 1905,
        "alt": "COCO 项目作品 3"
      },
      {
        "src": "assets/projects/p-2023-01/image-04-d2400.webp",
        "srcset": "assets/projects/p-2023-01/image-04-d1200.webp 1200w, assets/projects/p-2023-01/image-04-d2400.webp 2400w",
        "avifSrcset": "assets/projects/p-2023-01/image-04-d1200.avif 1200w, assets/projects/p-2023-01/image-04-d2400.avif 2400w",
        "width": 3000,
        "height": 1928,
        "alt": "COCO 项目作品 4"
      },
      {
        "src": "assets/projects/p-2023-01/image-05-d2400.webp",
        "srcset": "assets/projects/p-2023-01/image-05-d1200.webp 1200w, assets/projects/p-2023-01/image-05-d2400.webp 1800w",
        "avifSrcset": "assets/projects/p-2023-01/image-05-d1200.avif 1200w, assets/projects/p-2023-01/image-05-d2400.avif 1800w",
        "width": 1800,
        "height": 1012,
        "alt": "COCO 项目作品 5"
      }
    ]
  },
  {
    "id": "p-2023-02",
    "year": 2023,
    "name": "天赐",
    "cover": {
      "src": "assets/projects/p-2023-02/image-01-w1200.webp",
      "srcset": "assets/projects/p-2023-02/image-01-w640.webp 640w, assets/projects/p-2023-02/image-01-w1200.webp 1200w, assets/projects/p-2023-02/image-01-w1600.webp 1352w",
      "avifSrcset": "assets/projects/p-2023-02/image-01-w640.avif 640w, assets/projects/p-2023-02/image-01-w1200.avif 1200w, assets/projects/p-2023-02/image-01-w1600.avif 1352w",
      "width": 1352,
      "height": 2560,
      "alt": "天赐 项目作品 1"
    },
    "images": [
      {
        "src": "assets/projects/p-2023-02/image-01-w1200.webp",
        "srcset": "assets/projects/p-2023-02/image-01-w640.webp 640w, assets/projects/p-2023-02/image-01-w1200.webp 1200w, assets/projects/p-2023-02/image-01-w1600.webp 1352w",
        "avifSrcset": "assets/projects/p-2023-02/image-01-w640.avif 640w, assets/projects/p-2023-02/image-01-w1200.avif 1200w, assets/projects/p-2023-02/image-01-w1600.avif 1352w",
        "width": 1352,
        "height": 2560,
        "alt": "天赐 项目作品 1"
      }
    ]
  },
  {
    "id": "p-2023-03",
    "year": 2023,
    "name": "悸动",
    "cover": {
      "src": "assets/projects/p-2023-03/image-01-w1200.webp",
      "srcset": "assets/projects/p-2023-03/image-01-w640.webp 640w, assets/projects/p-2023-03/image-01-w1200.webp 1200w, assets/projects/p-2023-03/image-01-w1600.webp 1600w",
      "avifSrcset": "assets/projects/p-2023-03/image-01-w640.avif 640w, assets/projects/p-2023-03/image-01-w1200.avif 1200w, assets/projects/p-2023-03/image-01-w1600.avif 1600w",
      "width": 2560,
      "height": 1440,
      "alt": "悸动 项目作品 1"
    },
    "images": [
      {
        "src": "assets/projects/p-2023-03/image-01-w1200.webp",
        "srcset": "assets/projects/p-2023-03/image-01-w640.webp 640w, assets/projects/p-2023-03/image-01-w1200.webp 1200w, assets/projects/p-2023-03/image-01-w1600.webp 1600w",
        "avifSrcset": "assets/projects/p-2023-03/image-01-w640.avif 640w, assets/projects/p-2023-03/image-01-w1200.avif 1200w, assets/projects/p-2023-03/image-01-w1600.avif 1600w",
        "width": 2560,
        "height": 1440,
        "alt": "悸动 项目作品 1"
      }
    ]
  },
  {
    "id": "p-2023-04",
    "year": 2023,
    "name": "新昌",
    "cover": {
      "src": "assets/projects/p-2023-04/image-01-w1200.webp",
      "srcset": "assets/projects/p-2023-04/image-01-w640.webp 640w, assets/projects/p-2023-04/image-01-w1200.webp 1200w, assets/projects/p-2023-04/image-01-w1600.webp 1600w",
      "avifSrcset": "assets/projects/p-2023-04/image-01-w640.avif 640w, assets/projects/p-2023-04/image-01-w1200.avif 1200w, assets/projects/p-2023-04/image-01-w1600.avif 1600w",
      "width": 3387,
      "height": 1905,
      "alt": "新昌 项目作品 1"
    },
    "images": [
      {
        "src": "assets/projects/p-2023-04/image-01-w1200.webp",
        "srcset": "assets/projects/p-2023-04/image-01-w640.webp 640w, assets/projects/p-2023-04/image-01-w1200.webp 1200w, assets/projects/p-2023-04/image-01-w1600.webp 1600w",
        "avifSrcset": "assets/projects/p-2023-04/image-01-w640.avif 640w, assets/projects/p-2023-04/image-01-w1200.avif 1200w, assets/projects/p-2023-04/image-01-w1600.avif 1600w",
        "width": 3387,
        "height": 1905,
        "alt": "新昌 项目作品 1"
      },
      {
        "src": "assets/projects/p-2023-04/image-02-d2400.webp",
        "srcset": "assets/projects/p-2023-04/image-02-d1200.webp 1200w, assets/projects/p-2023-04/image-02-d2400.webp 2400w",
        "avifSrcset": "assets/projects/p-2023-04/image-02-d1200.avif 1200w, assets/projects/p-2023-04/image-02-d2400.avif 2400w",
        "width": 3387,
        "height": 1905,
        "alt": "新昌 项目作品 2"
      }
    ]
  },
  {
    "id": "p-2023-05",
    "year": 2023,
    "name": "田园",
    "cover": {
      "src": "assets/projects/p-2023-05/image-01-w1200.webp",
      "srcset": "assets/projects/p-2023-05/image-01-w640.webp 640w, assets/projects/p-2023-05/image-01-w1200.webp 1200w, assets/projects/p-2023-05/image-01-w1600.webp 1600w",
      "avifSrcset": "assets/projects/p-2023-05/image-01-w640.avif 640w, assets/projects/p-2023-05/image-01-w1200.avif 1200w, assets/projects/p-2023-05/image-01-w1600.avif 1600w",
      "width": 3384,
      "height": 2081,
      "alt": "田园 项目作品 1"
    },
    "images": [
      {
        "src": "assets/projects/p-2023-05/image-01-w1200.webp",
        "srcset": "assets/projects/p-2023-05/image-01-w640.webp 640w, assets/projects/p-2023-05/image-01-w1200.webp 1200w, assets/projects/p-2023-05/image-01-w1600.webp 1600w",
        "avifSrcset": "assets/projects/p-2023-05/image-01-w640.avif 640w, assets/projects/p-2023-05/image-01-w1200.avif 1200w, assets/projects/p-2023-05/image-01-w1600.avif 1600w",
        "width": 3384,
        "height": 2081,
        "alt": "田园 项目作品 1"
      }
    ]
  },
  {
    "id": "p-2023-06",
    "year": 2023,
    "name": "碧蒂妮",
    "cover": {
      "src": "assets/projects/p-2023-06/image-01-w1200.webp",
      "srcset": "assets/projects/p-2023-06/image-01-w640.webp 640w, assets/projects/p-2023-06/image-01-w1200.webp 1200w, assets/projects/p-2023-06/image-01-w1600.webp 1600w",
      "avifSrcset": "assets/projects/p-2023-06/image-01-w640.avif 640w, assets/projects/p-2023-06/image-01-w1200.avif 1200w, assets/projects/p-2023-06/image-01-w1600.avif 1600w",
      "width": 3000,
      "height": 3700,
      "alt": "碧蒂妮 项目作品 1"
    },
    "images": [
      {
        "src": "assets/projects/p-2023-06/image-01-w1200.webp",
        "srcset": "assets/projects/p-2023-06/image-01-w640.webp 640w, assets/projects/p-2023-06/image-01-w1200.webp 1200w, assets/projects/p-2023-06/image-01-w1600.webp 1600w",
        "avifSrcset": "assets/projects/p-2023-06/image-01-w640.avif 640w, assets/projects/p-2023-06/image-01-w1200.avif 1200w, assets/projects/p-2023-06/image-01-w1600.avif 1600w",
        "width": 3000,
        "height": 3700,
        "alt": "碧蒂妮 项目作品 1"
      }
    ]
  },
  {
    "id": "p-2023-07",
    "year": 2023,
    "name": "肥叔",
    "cover": {
      "src": "assets/projects/p-2023-07/image-01-w1200.webp",
      "srcset": "assets/projects/p-2023-07/image-01-w640.webp 640w, assets/projects/p-2023-07/image-01-w1200.webp 1200w, assets/projects/p-2023-07/image-01-w1600.webp 1600w",
      "avifSrcset": "assets/projects/p-2023-07/image-01-w640.avif 640w, assets/projects/p-2023-07/image-01-w1200.avif 1200w, assets/projects/p-2023-07/image-01-w1600.avif 1600w",
      "width": 3387,
      "height": 1905,
      "alt": "肥叔 项目作品 1"
    },
    "images": [
      {
        "src": "assets/projects/p-2023-07/image-01-w1200.webp",
        "srcset": "assets/projects/p-2023-07/image-01-w640.webp 640w, assets/projects/p-2023-07/image-01-w1200.webp 1200w, assets/projects/p-2023-07/image-01-w1600.webp 1600w",
        "avifSrcset": "assets/projects/p-2023-07/image-01-w640.avif 640w, assets/projects/p-2023-07/image-01-w1200.avif 1200w, assets/projects/p-2023-07/image-01-w1600.avif 1600w",
        "width": 3387,
        "height": 1905,
        "alt": "肥叔 项目作品 1"
      },
      {
        "src": "assets/projects/p-2023-07/image-02-d2400.webp",
        "srcset": "assets/projects/p-2023-07/image-02-d1200.webp 1200w, assets/projects/p-2023-07/image-02-d2400.webp 1800w",
        "avifSrcset": "assets/projects/p-2023-07/image-02-d1200.avif 1200w, assets/projects/p-2023-07/image-02-d2400.avif 1800w",
        "width": 1800,
        "height": 1100,
        "alt": "肥叔 项目作品 2"
      }
    ]
  },
  {
    "id": "p-2023-08",
    "year": 2023,
    "name": "酒鬼酒",
    "cover": {
      "src": "assets/projects/p-2023-08/image-01-w1200.webp",
      "srcset": "assets/projects/p-2023-08/image-01-w640.webp 640w, assets/projects/p-2023-08/image-01-w1200.webp 1200w, assets/projects/p-2023-08/image-01-w1600.webp 1600w",
      "avifSrcset": "assets/projects/p-2023-08/image-01-w640.avif 640w, assets/projects/p-2023-08/image-01-w1200.avif 1200w, assets/projects/p-2023-08/image-01-w1600.avif 1600w",
      "width": 3000,
      "height": 1265,
      "alt": "酒鬼酒 项目作品 1"
    },
    "images": [
      {
        "src": "assets/projects/p-2023-08/image-01-w1200.webp",
        "srcset": "assets/projects/p-2023-08/image-01-w640.webp 640w, assets/projects/p-2023-08/image-01-w1200.webp 1200w, assets/projects/p-2023-08/image-01-w1600.webp 1600w",
        "avifSrcset": "assets/projects/p-2023-08/image-01-w640.avif 640w, assets/projects/p-2023-08/image-01-w1200.avif 1200w, assets/projects/p-2023-08/image-01-w1600.avif 1600w",
        "width": 3000,
        "height": 1265,
        "alt": "酒鬼酒 项目作品 1"
      }
    ]
  },
  {
    "id": "p-2023-09",
    "year": 2023,
    "name": "阿水大杯茶",
    "cover": {
      "src": "assets/projects/p-2023-09/image-01-w1200.webp",
      "srcset": "assets/projects/p-2023-09/image-01-w640.webp 640w, assets/projects/p-2023-09/image-01-w1200.webp 1200w, assets/projects/p-2023-09/image-01-w1600.webp 1600w",
      "avifSrcset": "assets/projects/p-2023-09/image-01-w640.avif 640w, assets/projects/p-2023-09/image-01-w1200.avif 1200w, assets/projects/p-2023-09/image-01-w1600.avif 1600w",
      "width": 2560,
      "height": 1440,
      "alt": "阿水大杯茶 项目作品 1"
    },
    "images": [
      {
        "src": "assets/projects/p-2023-09/image-01-w1200.webp",
        "srcset": "assets/projects/p-2023-09/image-01-w640.webp 640w, assets/projects/p-2023-09/image-01-w1200.webp 1200w, assets/projects/p-2023-09/image-01-w1600.webp 1600w",
        "avifSrcset": "assets/projects/p-2023-09/image-01-w640.avif 640w, assets/projects/p-2023-09/image-01-w1200.avif 1200w, assets/projects/p-2023-09/image-01-w1600.avif 1600w",
        "width": 2560,
        "height": 1440,
        "alt": "阿水大杯茶 项目作品 1"
      },
      {
        "src": "assets/projects/p-2023-09/image-02-d2400.webp",
        "srcset": "assets/projects/p-2023-09/image-02-d1200.webp 1200w, assets/projects/p-2023-09/image-02-d2400.webp 2400w",
        "avifSrcset": "assets/projects/p-2023-09/image-02-d1200.avif 1200w, assets/projects/p-2023-09/image-02-d2400.avif 2400w",
        "width": 3387,
        "height": 1905,
        "alt": "阿水大杯茶 项目作品 2"
      }
    ]
  },
  {
    "id": "p-2022-01",
    "year": 2022,
    "name": "华泰",
    "cover": {
      "src": "assets/projects/p-2022-01/image-01-w1200.webp",
      "srcset": "assets/projects/p-2022-01/image-01-w640.webp 640w, assets/projects/p-2022-01/image-01-w1200.webp 1200w, assets/projects/p-2022-01/image-01-w1600.webp 1600w",
      "avifSrcset": "assets/projects/p-2022-01/image-01-w640.avif 640w, assets/projects/p-2022-01/image-01-w1200.avif 1200w, assets/projects/p-2022-01/image-01-w1600.avif 1600w",
      "width": 1800,
      "height": 2962,
      "alt": "华泰 项目作品 1"
    },
    "images": [
      {
        "src": "assets/projects/p-2022-01/image-01-w1200.webp",
        "srcset": "assets/projects/p-2022-01/image-01-w640.webp 640w, assets/projects/p-2022-01/image-01-w1200.webp 1200w, assets/projects/p-2022-01/image-01-w1600.webp 1600w",
        "avifSrcset": "assets/projects/p-2022-01/image-01-w640.avif 640w, assets/projects/p-2022-01/image-01-w1200.avif 1200w, assets/projects/p-2022-01/image-01-w1600.avif 1600w",
        "width": 1800,
        "height": 2962,
        "alt": "华泰 项目作品 1"
      }
    ]
  },
  {
    "id": "p-2022-02",
    "year": 2022,
    "name": "心相印",
    "cover": {
      "src": "assets/projects/p-2022-02/image-01-w1200.webp",
      "srcset": "assets/projects/p-2022-02/image-01-w640.webp 640w, assets/projects/p-2022-02/image-01-w1200.webp 1200w, assets/projects/p-2022-02/image-01-w1600.webp 1600w",
      "avifSrcset": "assets/projects/p-2022-02/image-01-w640.avif 640w, assets/projects/p-2022-02/image-01-w1200.avif 1200w, assets/projects/p-2022-02/image-01-w1600.avif 1600w",
      "width": 1800,
      "height": 1232,
      "alt": "心相印 项目作品 1"
    },
    "images": [
      {
        "src": "assets/projects/p-2022-02/image-01-w1200.webp",
        "srcset": "assets/projects/p-2022-02/image-01-w640.webp 640w, assets/projects/p-2022-02/image-01-w1200.webp 1200w, assets/projects/p-2022-02/image-01-w1600.webp 1600w",
        "avifSrcset": "assets/projects/p-2022-02/image-01-w640.avif 640w, assets/projects/p-2022-02/image-01-w1200.avif 1200w, assets/projects/p-2022-02/image-01-w1600.avif 1600w",
        "width": 1800,
        "height": 1232,
        "alt": "心相印 项目作品 1"
      },
      {
        "src": "assets/projects/p-2022-02/image-02-d2400.webp",
        "srcset": "assets/projects/p-2022-02/image-02-d1200.webp 1134w, assets/projects/p-2022-02/image-02-d2400.webp 1800w",
        "avifSrcset": "assets/projects/p-2022-02/image-02-d1200.avif 1134w, assets/projects/p-2022-02/image-02-d2400.avif 1800w",
        "width": 1800,
        "height": 1904,
        "alt": "心相印 项目作品 2"
      },
      {
        "src": "assets/projects/p-2022-02/image-03-d2400.webp",
        "srcset": "assets/projects/p-2022-02/image-03-d1200.webp 1200w, assets/projects/p-2022-02/image-03-d2400.webp 1800w",
        "avifSrcset": "assets/projects/p-2022-02/image-03-d1200.avif 1200w, assets/projects/p-2022-02/image-03-d2400.avif 1800w",
        "width": 1800,
        "height": 1270,
        "alt": "心相印 项目作品 3"
      }
    ]
  },
  {
    "id": "p-2022-03",
    "year": 2022,
    "name": "快鳄",
    "cover": {
      "src": "assets/projects/p-2022-03/image-01-w1200.webp",
      "srcset": "assets/projects/p-2022-03/image-01-w640.webp 640w, assets/projects/p-2022-03/image-01-w1200.webp 1200w, assets/projects/p-2022-03/image-01-w1600.webp 1600w",
      "avifSrcset": "assets/projects/p-2022-03/image-01-w640.avif 640w, assets/projects/p-2022-03/image-01-w1200.avif 1200w, assets/projects/p-2022-03/image-01-w1600.avif 1600w",
      "width": 1800,
      "height": 1329,
      "alt": "快鳄 项目作品 1"
    },
    "images": [
      {
        "src": "assets/projects/p-2022-03/image-01-w1200.webp",
        "srcset": "assets/projects/p-2022-03/image-01-w640.webp 640w, assets/projects/p-2022-03/image-01-w1200.webp 1200w, assets/projects/p-2022-03/image-01-w1600.webp 1600w",
        "avifSrcset": "assets/projects/p-2022-03/image-01-w640.avif 640w, assets/projects/p-2022-03/image-01-w1200.avif 1200w, assets/projects/p-2022-03/image-01-w1600.avif 1600w",
        "width": 1800,
        "height": 1329,
        "alt": "快鳄 项目作品 1"
      },
      {
        "src": "assets/projects/p-2022-03/image-02-d2400.webp",
        "srcset": "assets/projects/p-2022-03/image-02-d1200.webp 1200w, assets/projects/p-2022-03/image-02-d2400.webp 2400w",
        "avifSrcset": "assets/projects/p-2022-03/image-02-d1200.avif 1200w, assets/projects/p-2022-03/image-02-d2400.avif 2400w",
        "width": 5000,
        "height": 3451,
        "alt": "快鳄 项目作品 2"
      }
    ]
  },
  {
    "id": "p-2022-04",
    "year": 2022,
    "name": "智艾",
    "cover": {
      "src": "assets/projects/p-2022-04/image-01-w1200.webp",
      "srcset": "assets/projects/p-2022-04/image-01-w640.webp 640w, assets/projects/p-2022-04/image-01-w1200.webp 1200w, assets/projects/p-2022-04/image-01-w1600.webp 1600w",
      "avifSrcset": "assets/projects/p-2022-04/image-01-w640.avif 640w, assets/projects/p-2022-04/image-01-w1200.avif 1200w, assets/projects/p-2022-04/image-01-w1600.avif 1600w",
      "width": 2078,
      "height": 1169,
      "alt": "智艾 项目作品 1"
    },
    "images": [
      {
        "src": "assets/projects/p-2022-04/image-01-w1200.webp",
        "srcset": "assets/projects/p-2022-04/image-01-w640.webp 640w, assets/projects/p-2022-04/image-01-w1200.webp 1200w, assets/projects/p-2022-04/image-01-w1600.webp 1600w",
        "avifSrcset": "assets/projects/p-2022-04/image-01-w640.avif 640w, assets/projects/p-2022-04/image-01-w1200.avif 1200w, assets/projects/p-2022-04/image-01-w1600.avif 1600w",
        "width": 2078,
        "height": 1169,
        "alt": "智艾 项目作品 1"
      },
      {
        "src": "assets/projects/p-2022-04/image-02-d2400.webp",
        "srcset": "assets/projects/p-2022-04/image-02-d1200.webp 1200w, assets/projects/p-2022-04/image-02-d2400.webp 2400w",
        "avifSrcset": "assets/projects/p-2022-04/image-02-d1200.avif 1200w, assets/projects/p-2022-04/image-02-d2400.avif 2400w",
        "width": 4320,
        "height": 1620,
        "alt": "智艾 项目作品 2"
      }
    ]
  },
  {
    "id": "p-2022-05",
    "year": 2022,
    "name": "酷骑",
    "cover": {
      "src": "assets/projects/p-2022-05/image-01-w1200.webp",
      "srcset": "assets/projects/p-2022-05/image-01-w640.webp 640w, assets/projects/p-2022-05/image-01-w1200.webp 1200w, assets/projects/p-2022-05/image-01-w1600.webp 1600w",
      "avifSrcset": "assets/projects/p-2022-05/image-01-w640.avif 640w, assets/projects/p-2022-05/image-01-w1200.avif 1200w, assets/projects/p-2022-05/image-01-w1600.avif 1600w",
      "width": 2560,
      "height": 1445,
      "alt": "酷骑 项目作品 1"
    },
    "images": [
      {
        "src": "assets/projects/p-2022-05/image-01-w1200.webp",
        "srcset": "assets/projects/p-2022-05/image-01-w640.webp 640w, assets/projects/p-2022-05/image-01-w1200.webp 1200w, assets/projects/p-2022-05/image-01-w1600.webp 1600w",
        "avifSrcset": "assets/projects/p-2022-05/image-01-w640.avif 640w, assets/projects/p-2022-05/image-01-w1200.avif 1200w, assets/projects/p-2022-05/image-01-w1600.avif 1600w",
        "width": 2560,
        "height": 1445,
        "alt": "酷骑 项目作品 1"
      },
      {
        "src": "assets/projects/p-2022-05/image-02-d2400.webp",
        "srcset": "assets/projects/p-2022-05/image-02-d1200.webp 1200w, assets/projects/p-2022-05/image-02-d2400.webp 1800w",
        "avifSrcset": "assets/projects/p-2022-05/image-02-d1200.avif 1200w, assets/projects/p-2022-05/image-02-d2400.avif 1800w",
        "width": 1800,
        "height": 1013,
        "alt": "酷骑 项目作品 2"
      }
    ]
  }
];
